name: lint
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: lint
        if: ${{ runner.os == 'Linux' }}
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: 1.18
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
